version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 8080:15672

    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"

    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      timeout: 10s
      retries: 5

  bankme_api:
    build: ./bankme
    container_name: bankme_api
    tty: true
    stdin_open: true
    command: run start:dev

    working_dir: /app
    volumes:
      - ./bankme/src:/app/src
      - ./bankme/test:/app/test
      - ./bankme/prisma:/app/prisma
    ports:
      - 3001:3001

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      timeout: 10s
      retries: 5

    env_file:
     - ./.env

  web:
    container_name: 'bankme_web'
    build: ./web
    command: run dev
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./web/src:/app/src
    depends_on:
      - bankme_api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 10s
      retries: 5