name: Deploy to EC2 with Docker
on:
  push:
    branches: [pedro-henrique-a-silva-bankme-2024]
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Instala o node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instala as dependẽncias do backend
        run: npm run install:back

      - name: Roda os testes do backend
        run: npm run test:back
     
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
              rm -rf ~/aprove-me &&
              git clone -b pedro-henrique-a-silva-bankme-2024 git@github.com:pedro-henrique-a-silva/aprove-me.git &&
              echo "DB_NAME=${{ secrets.DB_NAME }}" >> ~/aprove-me/bankme/.env &&
              echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ~/aprove-me/bankme/.env &&
              echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ~/aprove-me/bankme/.env &&
              echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> ~/aprove-me/bankme/.env &&
              echo "URL=${{ secrets.URL }}" >> ~/aprove-me/bankme/.env &&
              echo "PORT=${{ secrets.PORT }}" >> ~/aprove-me/bankme/.env &&
              echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> ~/aprove-me/bankme/.env &&
              echo "NODE_ENV=production" >> ~/aprove-me/bankme/.env &&
              echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> ~/aprove-me/bankme/.env &&
              echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> ~/aprove-me/bankme/.env &&
              echo "SMTP_TO=${{ secrets.SMTP_TO }}" >> ~/aprove-me/bankme/.env &&
              echo "SMTP_FROM=${{ secrets.SMTP_FROM }}" >> ~/aprove-me/bankme/.env &&
              echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> ~/aprove-me/bankme/.env &&
              echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> ~/aprove-me/bankme/.env &&
              cp ~/aprove-me/bankme/.env ~/aprove-me/web/.env &&
              cd ~/aprove-me &&
              docker-compose down -v &&
              docker-compose up -d --build
            EOF


      # - name: Deploy do amazon
      #   run: |
      #     echo "${{ secrets.AWS_EC2_KEY }}" > private_key && chmod 600 private_key
      #     ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} '
      #       cd ~/apps && touch consegui.txt'
